name: Build on PR

on:
  push:
    branches:
      - matrix-test
  pull_request_target:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.base_ref }}

jobs:
  run:
    strategy:
      matrix:
        os: [ubuntu, windows, macos]
        node-version: ['16', '18', '20']
    name: Build on PR (${{ matrix.os }} Node.js ${{ matrix.node-version }})
    runs-on: ${{ matrix.os }}-latest
    if: github.actor == 'dependabot[bot]'
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install

      - uses: DamianReeves/write-file-action@v1.2
        with:
          path: .env
          contents: ${{ secrets.ENV }}
          write-mode: overwrite

      - run: npm run lint
      - run: npm test
      - run: npm run build
