name: Publish

on:
  workflow_dispatch:
  schedule:
    - cron: "0 9 * * *"

jobs:
  run:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - run: npm install

      - uses: DamianReeves/write-file-action@v1.0
        with:
          path: .env
          contents: ${{ secrets.ENV }}
          write-mode: overwrite

      - run: npm run lint
      - run: npm test
      - run: npm run build

      - uses: codfish/semantic-release-action@v1
        with:
          plugins: |
            [
              "@semantic-release/commit-analyzer",
              "@semantic-release/release-notes-generator",
              [
                "@semantic-release/npm", {
                  "pkgRoot": "dist"
                }
              ],
              "@semantic-release/github"
            ]
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
        continue-on-error: true
