name: Build on PR

on:
  pull_request:
    branches:
      - master

jobs:
  run:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 10
      - run: npm install

      - uses: DamianReeves/write-file-action@v1.0
        with:
          path: .env
          contents: ${{ secrets.ENV }}
          write-mode: overwrite
          
      - run: npm run build --if-present
      - run: npm test
